### ISSUE TITLE
Licensing on project

### ISSUE THREAD

**Issue by peterwoodworth** [ealush/flairup#9]
Hi there!

I've noticed there isn't a license on this project, I was wondering if it would be possible for you to update this project with a License that works for you. For example if you want a permissive license, you could attach the [MIT license](https://spdx.org/licenses/MIT.html) to this project as a LICENSE file. Would be helpful to know what rights we have when it comes to this software

Thank you!

**Comment by ealush** [comment]
So sorry @peterwoodworth, didn't think about it. I'll add MIT when I'm next to a computer. Thanks for reminding me.

**Comment by ealush** [comment]
@peterwoodworth added MIT. 0.0.38. Closing

**Comment by peterwoodworth** [comment]
Thanks a bunch @ealush, appreciate the quick turnaround 🙂
